AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/NumberedParametersLimit:
  Max: 2
Style/BlockDelimiters:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
