AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
