#!/usr/bin/env bash

SHELL_SOURCES=(
	common
	zsh
	scripts
)
GENERAL_SOURCES=(
	nvim
	fzf
	git
	ruby
	sqlite3
	ncdu
)
SWAY_SOURCES=( sway terminal )
ALL_SOURCES=( "${GENERAL_SOURCES[@]}" "${SHELL_SOURCES[@]}" "${SWAY_SOURCES[@]}" )
