#!/usr/bin/env bash

SHELL_SOURCES=(
	bash
	common
	zsh
)
GENERAL_SOURCES=(
	nvim
	fzf
	git
	ruby
	tmux
	vim
)
I3_SOURCES=( i3 )
SWAY_SOURCES=( sway foot )
ALL_SOURCES=( "${SHELL_SOURCES[@]}" "${GENERAL_SOURCES[@]}" "${SWAY_SOURCES[@]}" "${I3_SOURCES[@]}" )
