#!/usr/bin/env bash

SHELL_SOURCES=(
	# bash
	common
	zsh
)
GENERAL_SOURCES=(
	nvim
	fzf
	git
	ruby
	tmux
	# vim
)
SWAY_SOURCES=( sway terminal )
ALL_SOURCES=( "${GENERAL_SOURCES[@]}" "${SHELL_SOURCES[@]}" "${SWAY_SOURCES[@]}" )
